CC = gcc 
CFLAGS = -Wall -Wextra -O2 -Wno-deprecated-declarations
GTKFLAGS = `pkg-config --cflags --libs gtk+-2.0`

all : hddscviewer2.c
	xxd -i hddscviewer2.glade hddscviewer2_glade.h
	$(CC) $(CFLAGS) hddscviewer2.c -o hddscviewer $(GTKFLAGS)
	